### ISSUE TITLE
Fix disabled SampleJerseyRestfulServerApplicationTest broken since Boot 3 migration

### ISSUE THREAD

**Issue by faisal-dilawar** [hapifhir/hapi-fhir#7654]
## Summary

`SampleJerseyRestfulServerApplicationTest` has been disabled since the Spring Boot 3 upgrade with the note:

> *"This test stopped working when we upgraded to Boot 3 - Fixes welcome"*

## Root Cause

Four issues compound each other:

1. **No `ResourceConfig` bean** — Spring Boot 3 requires explicit Jersey resource registration. Boot 2 auto-discovered `@Component` JAX-RS beans; Boot 3 does not.

2. **`spring.factories` exclusion broken** — `FhirAutoConfiguration` is registered via the deprecated `spring.factories` mechanism. Boot 3.5 only recognises classes in `AutoConfiguration.imports` as excludable auto-configurations, so `@SpringBootApplication(exclude = {FhirAutoConfiguration.class})` throws `IllegalStateException`.

3. **`NullPointerException` at startup** — `AbstractJaxRsConformanceProvider.buildCapabilityStatement()` fires via `@EventListener(ContextRefreshedEvent.class)` before JAX-RS injects `@Context UriInfo`, causing a NPE on `getUriInfo().getBaseUri()`.

4. **Jersey version mismatch** — The project pins `jersey_version=3.0.3` (Jakarta EE 9 / Servlet 5.0). Spring Boot 3.x requires Jersey 3.1.x (Jakarta EE 10 / Servlet 6.0). The mixed versions cause `NoSuchMethodError: HttpServletResponse.setStatus(int, String)` at runtime.

## Fix (already implemented locally, ready to PR)

- Bump `jersey_version` from `3.0.3` to `3.1.11`
- Add `META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports` to `hapi-fhir-spring-boot-autoconfigure` (already done in #7443)
- Add `@Path("/Patient")` to `PatientResourceProvider`
- Add `JerseyConformanceProvider` (handles `/fhir/metadata`, defers `buildCapabilityStatement()` until first HTTP request)
- Add `JerseyConfig extends ResourceConfig` with `@ApplicationPath("/fhir")`
- Exclude `FhirAutoConfiguration` from the Jersey sample app
- Clean up `application.yml` (remove invalid `management.security.enabled`)
- Re-enable `SampleJerseyRestfulServerApplicationTest`

## Related

Discovered while working on #7443 (Spring Boot 3.5 EOL bump).
